rules:
  - id: dangerous-eval-usage
    pattern: eval(...)
    message: "Dangerous use of eval() detected - allows arbitrary code execution"
    severity: ERROR
    languages: [python]
    metadata:
      cwe: "CWE-95: Improper Neutralization of Directives in Dynamically Evaluated Code"
      owasp: "A03:2021 - Injection"

  - id: dangerous-exec-usage
    pattern: exec(...)
    message: "Dangerous use of exec() detected - allows arbitrary code execution"
    severity: ERROR
    languages: [python]
    metadata:
      cwe: "CWE-95"
      owasp: "A03:2021 - Injection"

  - id: shell-injection-subprocess
    pattern: subprocess.$FUNC(..., shell=True, ...)
    message: "Shell injection vulnerability - subprocess with shell=True is dangerous"
    severity: ERROR
    languages: [python]
    metadata:
      cwe: "CWE-78: OS Command Injection"
      owasp: "A03:2021 - Injection"

  - id: dangerous-pickle-load
    pattern: pickle.load(...)
    message: "Dangerous use of pickle.load() - can execute arbitrary code during deserialization"
    severity: ERROR
    languages: [python]
    metadata:
      cwe: "CWE-502: Deserialization of Untrusted Data"
      owasp: "A08:2021 - Software and Data Integrity Failures"

  - id: dangerous-os-system
    pattern: os.system(...)
    message: "Dangerous use of os.system() - allows command injection and arbitrary code execution"
    severity: ERROR
    languages: [python]
    metadata:
      cwe: "CWE-78: OS Command Injection"
      owasp: "A03:2021 - Injection"

  - id: hardcoded-secret
    patterns:
      - pattern-either:
          - pattern: $VAR = "sk-..."
          - pattern: $VAR = "...password..."
          - pattern: $VAR = "...api_key..."
          - pattern: $VAR = "...secret..."
    message: "Potential hardcoded secret detected"
    severity: WARNING
    languages: [python]
    metadata:
      cwe: "CWE-798: Use of Hard-coded Credentials"
      owasp: "A07:2021 - Identification and Authentication Failures"

  - id: bare-except-clause
    pattern: |
      try:
        ...
      except:
        ...
    message: "Bare except clause detected - catches all exceptions including system exits"
    severity: WARNING
    languages: [python]
    metadata:
      cwe: "CWE-396: Declaration of Catch for Generic Exception"

  - id: assert-for-validation
    pattern: assert $CONDITION, ...
    message: "Using assert for validation - can be disabled with -O flag"
    severity: WARNING
    languages: [python]
    paths:
      exclude:
        - "tests/"
    metadata:
      cwe: "CWE-703: Improper Check or Handling of Exceptional Conditions"

  - id: sql-injection-pattern
    pattern: |
      $QUERY = f"... VALUES ('{...}', '{...}', '{...}')"
    message: "Potential SQL injection - using f-string for SQL query construction"
    severity: ERROR
    languages: [python]
    metadata:
      cwe: "CWE-89: SQL Injection"
      owasp: "A03:2021 - Injection"

  - id: compile-with-eval
    pattern: |
      compile(..., '<string>', 'eval')
    message: "Dangerous use of compile() with eval mode - code injection risk"
    severity: ERROR
    languages: [python]
    metadata:
      cwe: "CWE-95"
